-- Vider la table des projets actuels (données fictives)
DELETE FROM projects;

-- Insérer les 17 vrais projets
INSERT INTO projects (title_fr, title_en, description_fr, description_en, category_fr, category_en, date_start, is_published, cover_image) VALUES
('Entretiens des candidats bénévoles', 'Volunteer Candidate Interviews', 'Entretiens de sélection des candidats bénévoles dans le cadre du renforcement des équipes de GESIS pour les projets à venir.', 'Selection interviews for volunteer candidates as part of strengthening GESIS teams for upcoming projects.', 'Droits & Inclusion', 'Rights & Inclusion', '2026-03-14', true, 'https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&q=80&w=800'),
('Célébration de la Journée Internationale des Droits de la Femme', 'International Women''s Day Celebration', 'GESIS célèbre le 8 mars 2026 la Journée Internationale des Droits de la Femme, réaffirmant son engagement pour l''égalité de genre et l''autonomisation des femmes dans nos communautés.', 'GESIS celebrates International Women''s Day on March 8, 2026, reaffirming its commitment to gender equality and women''s empowerment in our communities.', 'Droits & Inclusion', 'Rights & Inclusion', '2026-03-08', true, 'https://images.unsplash.com/photo-1596423735880-5f2a689b903e?auto=format&fit=crop&q=80&w=800'),
('Assemblée Générale Ordinaire', 'Ordinary General Assembly', 'Tenue de l''Assemblée Générale Ordinaire de GESIS — bilan des activités, validation des orientations et renouvellement des engagements des membres.', 'Holding of the GESIS Ordinary General Assembly — activity report, validation of orientations, and renewal of members'' commitments.', 'Institutionnel', 'Institutional', '2026-02-15', true, 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=800'),
('Conférence sur l''implication de la jeunesse — Lagbè', 'Conference on Youth Involvement — Lagbè', 'Animation d''une conférence au profit des étudiants de Lagbè sur l''implication de la jeunesse pour le développement de leur communauté.', 'Hosting a conference for Lagbè students on youth involvement for the development of their community.', 'Éducation', 'Education', '2026-02-14', true, 'https://images.unsplash.com/photo-1523580494112-071d1e21d80c?auto=format&fit=crop&q=80&w=800'),
('Webinaire sur le Militantisme — Youth For Peace Benin', 'Webinar on Activism — Youth For Peace Benin', 'Animation d''un webinaire sur le militantisme pour le compte de Youth For Peace Benin, mobilisant la jeunesse autour des valeurs d''engagement citoyen et de plaidoyer pacifique.', 'Hosting a webinar on activism for Youth For Peace Benin, mobilizing youth around the values of civic engagement and peaceful advocacy.', 'Paix & Solidarité', 'Peace & Solidarity', '2026-02-07', true, 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&q=80&w=800'),
('Campagne de recrutement de bénévoles', 'Volunteer Recruitment Campaign', 'Campagne de recrutement de bénévoles pour renforcer les équipes de GESIS sur le terrain dans le cadre des projets à venir.', 'Volunteer recruitment campaign to strengthen GESIS field teams for upcoming projects.', 'Institutionnel', 'Institutional', '2026-02-01', true, 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&q=80&w=800'),
('Campagne Digitale pour la Paix — Élections 2026', 'Digital Peace Campaign — 2026 Elections', 'Campagne digitale pour la paix dans le cadre des élections couplées de janvier 2026. Nos membres ont également participé au processus électoral comme observateurs et membres de postes de vote.', 'Digital campaign for peace in the context of the January 2026 joint elections. Our members also participated in the electoral process as observers and polling station members.', 'Paix & Solidarité', 'Peace & Solidarity', '2026-01-10', true, 'https://images.unsplash.com/photo-1529209076408-5a115ec9f1c6?auto=format&fit=crop&q=80&w=800'),
('Université de la Nature — Ecoversities Afrika', 'University of Nature — Ecoversities Afrika', 'Participation de GESIS à l''université de la nature couplée avec Ecoversities Afrika, espace de réflexion et d''échange autour des enjeux environnementaux et du développement durable en Afrique.', 'GESIS participation in the University of Nature coupled with Ecoversities Afrika, a space for reflection and exchange around environmental issues and sustainable development in Africa.', 'Environnement', 'Environment', '2026-01-03', true, 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800'),
('Attestation de Reconnaissance — Festisol Ouémé 2025', 'Certificate of Recognition — Festisol Ouémé 2025', 'Réception de l''attestation de reconnaissance décernée à l''ONG GESIS pour son implication remarquable dans la réussite du Festival des Solidarités Ouémé 2025.', 'Receipt of the certificate of recognition awarded to GESIS NGO for its remarkable involvement in the success of the Ouémé Solidarity Festival 2025.', 'Institutionnel', 'Institutional', '2025-12-03', true, 'https://images.unsplash.com/photo-1589330694653-afa7dc030bc6?auto=format&fit=crop&q=80&w=800'),
('Conférence : Leadership, confiance et réussite', 'Conference: Leadership, Trust and Success', 'Conférence sur le thème "Leadership, confiance et réussite à l''école et dans la vie", organisée dans le cadre du Festival des Solidarités Ouémé 2025.', 'Conference on the theme "Leadership, trust and success at school and in life", organized as part of the Ouémé Solidarity Festival 2025.', 'Éducation', 'Education', '2025-11-28', true, 'https://images.unsplash.com/photo-1511629091441-ee46146481b6?auto=format&fit=crop&q=80&w=800'),
('Programme "L''Éducation c''est l''Avenir" — CEG Mededjonou', 'Program "Education is the Future" — CEG Mededjonou', 'Discussion autour du thème "Mon avenir commence maintenant : réussir à l''école et dans la vie" avec les élèves du premier cycle au CEG Mededjonou, dans le cadre du Festisol Ouémé 2025.', 'Discussion around the theme "My future starts now: succeeding at school and in life" with junior high students at CEG Mededjonou, as part of Festisol Ouémé 2025.', 'Éducation', 'Education', '2025-11-26', true, 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&q=80&w=800'),
('Nomination de l''équipe projet — Programme d''Impact Scolaire', 'Project Team Appointment — School Impact Program', 'Nomination officielle des membres de l''équipe projet pour le Programme d''impact scolaire "L''Éducation c''est l''Avenir".', 'Official appointment of the project team members for the School Impact Program "Education is the Future".', 'Institutionnel', 'Institutional', '2025-11-22', true, 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800'),
('Festival des Solidarités dans l''Ouémé — Festisol 2025', 'Solidarity Festival in Ouémé — Festisol 2025', 'Participation active de GESIS au Festival des Solidarités dans le département de l''Ouémé, avec plusieurs activités de sensibilisation, de formation et de mobilisation communautaire.', 'Active participation of GESIS in the Solidarity Festival in the Ouémé department, with several awareness-raising, training, and community mobilization activities.', 'Paix & Solidarité', 'Peace & Solidarity', '2025-11-14', true, 'https://images.unsplash.com/photo-1529156069898-49953eb1b5ae?auto=format&fit=crop&q=80&w=800'),
('Célébration de la Journée Internationale des Enseignants', 'International Teachers'' Day Celebration', 'Hommage aux femmes et hommes qui œuvrent chaque jour pour l''éducation des jeunes générations au Bénin, à l''occasion de la Journée Internationale des Enseignants.', 'Tribute to the women and men who work every day for the education of young generations in Benin, on the occasion of International Teachers'' Day.', 'Éducation', 'Education', '2025-10-05', true, 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800'),
('Assemblée Générale Constitutive', 'Constituent General Assembly', 'Adoption officielle des statuts et du règlement intérieur de l''ONG GESIS, élection du Conseil d''Administration, conformément à la loi n° 2025-19 du 22 juillet 2025.', 'Official adoption of the statutes and internal regulations of the GESIS NGO, election of the Board of Directors, in accordance with law no. 2025-19 of July 22, 2025.', 'Institutionnel', 'Institutional', '2025-09-28', true, 'https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?auto=format&fit=crop&q=80&w=800'),
('Journée Internationale de la Paix', 'International Day of Peace', 'Participation de GESIS à la Journée Internationale de la Paix, affirmant son engagement pour la cohésion sociale et la culture de la paix au Bénin.', 'GESIS participation in the International Day of Peace, affirming its commitment to social cohesion and the culture of peace in Benin.', 'Paix & Solidarité', 'Peace & Solidarity', '2025-09-21', true, 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&q=80&w=800'),
('Adhésion à Youth For Peace Bénin', 'Membership in Youth For Peace Benin', 'GESIS rejoint officiellement la plateforme nationale Youth For Peace Bénin et intègre la Commission en charge de la communication et du plaidoyer pour la paix.', 'GESIS officially joins the national platform Youth For Peace Benin and becomes part of the Commission in charge of communication and advocacy for peace.', 'Paix & Solidarité', 'Peace & Solidarity', '2025-08-15', true, 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&q=80&w=800');
